version: "3.3"
services:
  cohend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn workspace gatsby-theme-rpsych-cohend gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
     - .:/app
     - /app/node_modules